// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'CJW_2024001761.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyRA6Z5n7Pibczsjs1E6E5OHePuPvkyik',
    appId: '1:279353768174:web:b51a3f1f3dce6f78ec9bff',
    messagingSenderId: '279353768174',
    projectId: 'flutter-induk-2024001761',
    authDomain: 'flutter-induk-2024001761.firebaseapp.com',
    storageBucket: 'flutter-induk-2024001761.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaIE45RjMFajXxw9HXmzy2EDBvMJTUcM4',
    appId: '1:279353768174:android:f3d51905ebd5d123ec9bff',
    messagingSenderId: '279353768174',
    projectId: 'flutter-induk-2024001761',
    storageBucket: 'flutter-induk-2024001761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbKgyeWDBODCHF_ZJafr5a2V3Oce9TWgY',
    appId: '1:279353768174:ios:b36daed840efb3deec9bff',
    messagingSenderId: '279353768174',
    projectId: 'flutter-induk-2024001761',
    storageBucket: 'flutter-induk-2024001761.firebasestorage.app',
    iosBundleId: 'com.example.flutterLab2024001761',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbKgyeWDBODCHF_ZJafr5a2V3Oce9TWgY',
    appId: '1:279353768174:ios:b36daed840efb3deec9bff',
    messagingSenderId: '279353768174',
    projectId: 'flutter-induk-2024001761',
    storageBucket: 'flutter-induk-2024001761.firebasestorage.app',
    iosBundleId: 'com.example.flutterLab2024001761',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyRA6Z5n7Pibczsjs1E6E5OHePuPvkyik',
    appId: '1:279353768174:web:5d5c601220490157ec9bff',
    messagingSenderId: '279353768174',
    projectId: 'flutter-induk-2024001761',
    authDomain: 'flutter-induk-2024001761.firebaseapp.com',
    storageBucket: 'flutter-induk-2024001761.firebasestorage.app',
  );
}
